#:schema node_modules/wrangler/config-schema.json
name = "thola-kimonganga-ui"
compatibility_date = "2024-05-12"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
VITE_MAPBOX_API_KEY="pk.eyJ1IjoieWltbmFpLWRldiIsImEiOiJjbHduam00ZTAxdmF3MmtucmVwd3h0cGg5In0.Zj1QD6cNPxS_l1wdLiSJKA"
VITE_STRIPE_PUBLISHABLE_TEST_KEY="pk_test_51PBkDUDr4Gujlf6fCZku360mljWIQDUvukhGuVFzh8eKxz0Ev94IE7zEJeFRUXEmMGTclPbee8VoarH2J20M740S00FoBsFg5n"
VITE_STRIPE_PRICING_TABLE_TEST_ID="prctbl_1PLTUyDr4Gujlf6f9s01jZ4R"

[env.production.vars]
VITE_MAPBOX_API_KEY="pk.eyJ1IjoieWltbmFpLWRldiIsImEiOiJjbHduam00ZTAxdmF3MmtucmVwd3h0cGg5In0.Zj1QD6cNPxS_l1wdLiSJKA"
VITE_STRIPE_PUBLISHABLE_TEST_KEY="pk_test_51PBkDUDr4Gujlf6fCZku360mljWIQDUvukhGuVFzh8eKxz0Ev94IE7zEJeFRUXEmMGTclPbee8VoarH2J20M740S00FoBsFg5n"
VITE_STRIPE_PRICING_TABLE_TEST_ID="prctbl_1PLTUyDr4Gujlf6f9s01jZ4R"

