name: Run all tests
run-name: ${{ github.actor }} is running tests
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Test Application Wide Formatting"]
    types:
      - completed

jobs:
  check-app-tests:
    runs-on: ubuntu-latest
    default:
      run:
        working-directory: packages/thola-kimonganga-ui
    needs: Test Application Wide Formatting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: pnpm run test
