name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Test Application Wide Formatting"]
    types:
      - completed

jobs:
  check-app-formatting:
    name: Test Application Wide Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/thola-kimonganga-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Check formatting and linting
        run: |
          pnpm run check && pnpm run format && pnpm run lint

  check-app-tests:
    name: Run all tests
    runs-on: ubuntu-latest
    needs: check-app-formatting
    steps:
       - name: List working directory
        run: ls -la
        
      - name: Confirm Formatting
        run: echo "App formatted correctly"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests
        run: npm run test

  check-deploy-on-cloudflare:
    name: Deploy Application on cloudflare pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/thola-kimonganga-ui
    needs: check-app-tests
    steps:
      - name: Tests completed
        run: echo "All tests passed successfully"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy application
        run: npm run deploy
