name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Test Application Wide Formatting"]
    types:
      - completed

jobs:
  check-app-formatting:
    name: Test Application Wide Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/thola-kimonganga-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and Check formatting and linting
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run check && pnpm run format && pnpm run lint
      - name: Format complete
        run: echo "App formatted correctly"

      - name: Run tests
        run: pnpm run test

      - name: Tests complete
        run: echo "All tests passed successfully"

      - name: Deploy application
        run: pnpm run deploy