name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-thola-kimonganga-ui:
    name: Test Thola Kimonganga UI Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/thola-kimonganga-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and Check formatting and linting
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run check && pnpm run format && pnpm run lint
      - name: Format complete
        run: echo "App formatted correctly"

      - name: Deploy application
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: pnpm run deploy
  deploy-soundex-code-generator:
    name: Test Soundex Code Generator
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/soundex-code-generator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and Check formatting and linting
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run test
      - name: Test complete
        run: echo "Tested Soundex Code Generator"

      - name: Deploy application
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: pnpm run deploy
